**Task: Which US state has the highest number of accidents,and a description of the accidents that usually occur in that state.**

### Load Data

In [1]:
import pandas as pd

df = pd.read_csv("/kaggle/input/us-accidents/US_Accidents_Dec20.csv")

In [2]:
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4232541 entries, 0 to 4232540
Data columns (total 49 columns):
ID                       object
Source                   object
TMC                      float64
Severity                 int64
Start_Time               object
End_Time                 object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description              object
Number                   float64
Street                   object
Side                     object
City                     object
County                   object
State                    object
Zipcode                  object
Country                  object
Timezone                 object
Airport_Code             object
Weather_Timestamp        object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction           object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition        object
Amenity                  bool
Bump                     bool
Crossing                 bool
Give_Way                 bool
Junction                 bool
No_Exit                  bool
Railway                  bool
Roundabout               bool
Station                  bool
Stop                     bool
Traffic_Calming          bool
Traffic_Signal           bool
Turning_Loop             bool
Sunrise_Sunset           object
Civil_Twilight           object
Nautical_Twilight        object
Astronomical_Twilight    object
dtypes: bool(13), float64(14), int64(1), object(21)
memory usage: 1.2+ GB
None

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
print(df.shape)
df.columns

(4232541, 49)

Index(['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [4]:
number_of_duplicate = df[df.duplicated()]
number_of_duplicate.count()

ID                       0
Source                   0
TMC                      0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
End_Lat                  0
End_Lng                  0
Distance(mi)             0
Description              0
Number                   0
Street                   0
Side                     0
City                     0
County                   0
State                    0
Zipcode                  0
Country                  0
Timezone                 0
Airport_Code             0
Weather_Timestamp        0
Temperature(F)           0
Wind_Chill(F)            0
Humidity(%)              0
Pressure(in)             0
Visibility(mi)           0
Wind_Direction           0
Wind_Speed(mph)          0
Precipitation(in)        0
Weather_Condition        0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Sunrise_Sunset           0
Civil_Twilight           0
Nautical_Twilight        0
Astronomical_Twilight    0
dtype: int64

In [5]:
df.isnull().sum()

ID                             0
Source                         0
TMC                      1516064
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  2716477
End_Lng                  2716477
Distance(mi)                   0
Description                    2
Number                   2687949
Street                         0
Side                           0
City                         137
County                         0
State                          0
Zipcode                     1292
Country                        0
Timezone                    4615
Airport_Code                8973
Weather_Timestamp          62644
Temperature(F)             89900
Wind_Chill(F)            1896001
Humidity(%)                95467
Pressure(in)               76384
Visibility(mi)             98668
Wind_Direction             83611
Wind_Speed(mph)           479326
Precipitation(in)        2065589
Weather_Condition          98383
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset               141
Civil_Twilight               141
Nautical_Twilight            141
Astronomical_Twilight        141
dtype: int64

In [8]:
print(df.describe())

                TMC      Severity     Start_Lat     Start_Lng       End_Lat  \
count  2.716477e+06  4.232541e+06  4.232541e+06  4.232541e+06  1.516064e+06
mean   2.083517e+02  2.305035e+00  3.639782e+01 -9.546420e+01  3.690061e+01
std    2.124413e+01  5.332261e-01  4.964404e+00  1.735319e+01  5.165629e+00
min    2.000000e+02  1.000000e+00  2.455527e+01 -1.246238e+02  2.457011e+01
25%    2.010000e+02  2.000000e+00  3.352058e+01 -1.173570e+02  3.385420e+01
50%    2.010000e+02  2.000000e+00  3.582542e+01 -9.002078e+01  3.735134e+01
75%    2.010000e+02  3.000000e+00  4.018313e+01 -8.084682e+01  4.072593e+01
max    4.060000e+02  4.000000e+00  4.900220e+01 -6.711317e+01  4.907500e+01

            End_Lng  Distance(mi)        Number  Temperature(F)  \
count  1.516064e+06  4.232541e+06  1.544592e+06    4.142641e+06
mean  -9.859901e+01  3.357021e-01  6.141507e+03    6.147799e+01
std    1.849590e+01  1.602143e+00  1.492268e+04    1.852586e+01
min   -1.244978e+02  0.000000e+00  0.000000e+00   -8.900000e+01
25%   -1.182077e+02  0.000000e+00  8.980000e+02    4.900000e+01
50%   -9.437987e+01  0.000000e+00  2.890000e+03    6.300000e+01
75%   -8.087449e+01  8.900000e-02  7.330000e+03    7.520000e+01
max   -6.710924e+01  4.417500e+02  9.999997e+06    2.030000e+02

       Wind_Chill(F)   Humidity(%)  Pressure(in)  Visibility(mi)  \
count   2.336540e+06  4.137074e+06  4.156157e+06    4.133873e+06
mean    5.489319e+01  6.567422e+01  2.969371e+01    9.111991e+00
std     2.272355e+01  2.272342e+01  8.639260e-01    2.817582e+00
min    -8.900000e+01  1.000000e+00  0.000000e+00    0.000000e+00
25%     3.800000e+01  4.900000e+01  2.964000e+01    1.000000e+01
50%     5.800000e+01  6.800000e+01  2.993000e+01    1.000000e+01
75%     7.300000e+01  8.500000e+01  3.008000e+01    1.000000e+01
max     1.890000e+02  1.000000e+02  5.804000e+01    1.400000e+02

       Wind_Speed(mph)  Precipitation(in)
count     3.753215e+06       2.166952e+06
mean      7.903433e+00       1.244719e-02
std       5.330998e+00       1.637154e-01
min       0.000000e+00       0.000000e+00
25%       4.600000e+00       0.000000e+00
50%       7.000000e+00       0.000000e+00
75%       1.040000e+01       0.000000e+00
max       9.840000e+02       2.500000e+01

In [ ]:
df.State.value_counts()